CREATE TABLE "app_modul" (
	"id_modul" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_modul_id_modul_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"nama_modul" varchar(25) NOT NULL,
	"icons" varchar(30) NOT NULL,
	"icons2" varchar(30),
	"color" varchar(20)
);
--> statement-breakpoint
CREATE TABLE "app_role_menu" (
	"id_role" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app_role_menu_id_role_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_menu" integer NOT NULL,
	"id_modul" integer NOT NULL,
	"id_user" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "call_setting" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "call_setting_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user" integer,
	"nama" varchar(75),
	"bulan" varchar(20),
	"input_set" varchar(50),
	"jumlah" integer,
	"created_date" timestamp,
	"created_by" integer,
	"updated_date" timestamp,
	"updated_by" integer
);
--> statement-breakpoint
CREATE TABLE "call_target_class" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "call_target_class_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"jabatan" varchar(15) NOT NULL,
	"class" varchar(5) NOT NULL,
	"target" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "call_target_hari" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "call_target_hari_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"jabatan" varchar(20) NOT NULL,
	"divisi" varchar(50) NOT NULL,
	"dokter" integer NOT NULL,
	"non_dokter" integer,
	"periode_awal" date,
	"periode_akhir" date
);
--> statement-breakpoint
CREATE TABLE "call_target_list" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "call_target_list_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"jabatan" varchar(20) NOT NULL,
	"divisi" varchar(50) NOT NULL,
	"dokter" integer NOT NULL,
	"non_dokter" integer,
	"periode_awal" date,
	"periode_akhir" date
);
--> statement-breakpoint
CREATE TABLE "call_version" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "call_version_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"version" varchar(20),
	"link_apk" varchar(100)
);
--> statement-breakpoint
CREATE TABLE "data_pegawai" (
	"rowid" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "data_pegawai_rowid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id" varchar(10) NOT NULL,
	"nik" varchar(20),
	"nama" varchar(200) NOT NULL,
	"jabatan" varchar(50) NOT NULL,
	"divisi" varchar(30),
	"rayon" varchar(200),
	"rayon_dm" varchar(150),
	"region" varchar(50),
	"homebase" varchar(50),
	"lokasi" varchar(30),
	"lokasi_absen" varchar(30),
	"telepon" varchar(30),
	"email" varchar(250),
	"status" varchar(20),
	"keterangan" varchar(200),
	"tgl_masuk" date,
	"tgl_keluar" date,
	"tanda_tangan" varchar(50),
	"id_finger" integer,
	"id_user" integer
);
--> statement-breakpoint
CREATE TABLE "data_product" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "data_product_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_product" varchar(25) NOT NULL,
	"nama_product" varchar(50) NOT NULL,
	"komposisi" varchar(400),
	"kemasan" varchar(70),
	"isi_box" integer,
	"group_product" varchar(30),
	"jenis_product" varchar(15) NOT NULL,
	"keterangan_harga" varchar(50),
	"class_terapi" varchar(50),
	"product_hj" varchar(10),
	"sub_divisi" varchar(30),
	"sub_divisi_sales" varchar(30),
	"divisi" varchar(30) NOT NULL,
	"set_divisi" varchar(30),
	"harga" integer NOT NULL,
	"harga_jadi" integer,
	"harga_reg_1" integer,
	"harga_reg_2" integer,
	"harga_reg_3" integer,
	"harga_reg_4" integer,
	"harga_reg_5" integer,
	"harga_reg_6" integer,
	"harga_reg_7" integer,
	"penyeragaman_product" varchar(50),
	"brand_product" varchar(50),
	"product_fokus" varchar(20),
	"periode_awal" date,
	"periode_akhir" date,
	"status" varchar(20),
	"attachment" varchar(250),
	"product_detail_link" varchar(255),
	"tgl_masa_berlaku" date,
	"created_date" timestamp,
	"created_by" integer,
	"updated_date" timestamp,
	"updated_by" integer
);
--> statement-breakpoint
CREATE TABLE "data_spec_dr" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "data_spec_dr_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"spec" varchar(50) NOT NULL,
	"gelar" varchar(20),
	"keterangan" varchar(50)
);
--> statement-breakpoint
CREATE TABLE "list_dokter_visit_new" (
	"ID" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "list_dokter_visit_new_ID_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ID_PEG" integer NOT NULL,
	"ID_FF" varchar(15) NOT NULL,
	"NAMA_FF" varchar(200) NOT NULL,
	"RAYON" varchar(200) NOT NULL,
	"DISTRIK" varchar(200) NOT NULL,
	"REGION" varchar(30) NOT NULL,
	"DIVISI" varchar(30) NOT NULL,
	"SEGMEN_MD" integer NOT NULL,
	"ID_MCL" integer NOT NULL,
	"ID_MD" varchar(30),
	"NAMA_DOKTER" varchar(200) NOT NULL,
	"NAMA_NON_DOKTER" varchar(150),
	"NO_STR" varchar(100),
	"SPEC" varchar(50) NOT NULL,
	"CLASS" varchar(5),
	"KODE_OUTLET_UNION" varchar(20) NOT NULL,
	"INSTITUSI" varchar(200),
	"KOORDINAT_INSTITUSI" varchar(100),
	"WILAYAH" varchar(20),
	"WILAYAH_DM" varchar(20),
	"WILAYAH_RSM" varchar(20),
	"HARI_PRAKTEK" varchar(100),
	"JAM_MULAI_PRAKTEK" time,
	"JAM_SELESAI_PRAKTEK" time,
	"DURASI_PRAKTEK" varchar(50),
	"ALAMAT_PRAKTEK" varchar(250),
	"KOTA" varchar(50),
	"ALAMAT_RUMAH" text,
	"NO_TELP_DOKTER" varchar(15),
	"HUT" date NOT NULL,
	"PROD_DETAILING_1" varchar(50),
	"PROD_DETAILING_2" varchar(50),
	"PROD_DETAILING_3" varchar(50),
	"PROD_DETAILING_4" varchar(50),
	"PROD_DETAILING_5" varchar(50),
	"PROD_DETAILING_6" varchar(50),
	"PROD_DETAILING_7" varchar(50),
	"PROD_DETAILING_8" varchar(50),
	"PROD_DETAILING_9" varchar(50),
	"PROD_DETAILING_10" varchar(50),
	"STATUS_MD" varchar(15),
	"DIBERIKAN_RBP" varchar(15),
	"JENIS_RBP" varchar(50),
	"KETERANGAN" varchar(150),
	"CREATED_DATE" timestamp,
	"CREATED_BY" integer,
	"UPDATED_DATE" timestamp,
	"UPDATED_BY" integer,
	"check_dm" integer,
	"check_dm_date" timestamp,
	"check_rsm" integer,
	"check_rsm_date" timestamp,
	"revisi_dm" integer,
	"comment_revisi_dm" text,
	"revisi_rsm" integer,
	"comment_revisi_rsm" text,
	"note" varchar(100)
);
--> statement-breakpoint
CREATE TABLE "struktur" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "struktur_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"id_mr" varchar(15),
	"id_peg_mr" integer,
	"rayon_mr" varchar(220) NOT NULL,
	"golongan" varchar(15) NOT NULL,
	"divisi" varchar(20) NOT NULL,
	"id_dm" varchar(15),
	"id_peg_dm" integer,
	"rayon_dm" varchar(100) NOT NULL,
	"id_rsm" varchar(15),
	"id_peg_rsm" integer,
	"region" varchar(15) NOT NULL,
	"id_som" varchar(15),
	"id_peg_som" integer,
	"id_mm" varchar(15),
	"id_peg_mm" integer,
	"id_dmd" varchar(15),
	"id_peg_dmd" integer,
	"id_md" varchar(15),
	"id_peg_md" integer,
	"id_vp" varchar(15),
	"id_peg_vp" integer,
	"id_adminda" varchar(15),
	"kantor_cabang" varchar(25),
	"periode_awal" date NOT NULL,
	"periode_akhir" date NOT NULL,
	"created_date" timestamp,
	"created_by" integer,
	"updated_date" timestamp,
	"updated_by" integer
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"username" varchar(150) NOT NULL,
	"status" varchar(15),
	"email" varchar(255),
	"email_verified_at" timestamp,
	"password" varchar(255) NOT NULL,
	"password_view" varchar(100),
	"remember_token" varchar(100),
	"created_at" timestamp,
	"updated_at" timestamp
);
--> statement-breakpoint
CREATE TABLE "call_list" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"id_mcl" integer NOT NULL,
	"periode" date,
	"is_visited" boolean DEFAULT false NOT NULL,
	"nama_dokter" varchar(255) NOT NULL,
	"spec" varchar(255) NOT NULL,
	"segmen" varchar(50) NOT NULL,
	"class" varchar(5),
	"target_visit" integer,
	"wilayah" varchar(30),
	"id_peg" integer NOT NULL,
	"id_ff" varchar(15) NOT NULL,
	"approval" varchar(15),
	"approval_by" integer,
	"approval_date" timestamp,
	"approval_comment" varchar(100),
	"keterangan" varchar(30),
	"note" varchar(150),
	"created_by" integer,
	"updated_by" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "call_list_history" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"call_list_id" uuid NOT NULL,
	"id_peg" integer NOT NULL,
	"action_type" varchar(20) NOT NULL,
	"action_date" timestamp with time zone DEFAULT now() NOT NULL,
	"old_id_mcl" integer,
	"new_id_mcl" integer,
	"old_nama_dokter" varchar(255),
	"new_nama_dokter" varchar(255),
	"old_spec" varchar(255),
	"new_spec" varchar(255),
	"old_class" varchar(5),
	"new_class" varchar(5),
	"old_segmen" varchar(50),
	"new_segmen" varchar(50),
	"old_wilayah" varchar(30),
	"new_wilayah" varchar(30),
	"old_target_visit" integer,
	"new_target_visit" integer,
	"reason" varchar(255),
	"ip_address" varchar(45),
	"user_agent" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "call_plan_actual" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"id_peg" integer NOT NULL,
	"id_ff" varchar(15) NOT NULL,
	"nama_ff" varchar(200) NOT NULL,
	"divisi" varchar(30),
	"id_mcl" integer,
	"nama_dokter" varchar(150),
	"spec" varchar(50),
	"segmen_md" integer,
	"class" varchar(5),
	"institusi" varchar(200),
	"alamat_praktek" varchar(250),
	"koordinat_institusi" varchar(100),
	"tgl_plan" date,
	"waktu" time,
	"product_list" text,
	"keterangan" varchar(500),
	"tgl_actual" date,
	"waktu_actual" time,
	"koor_visit" varchar(100),
	"stt_koor" integer,
	"status" varchar(30),
	"foto" varchar(250),
	"foto_link" varchar(500),
	"tanda_tangan" varchar(250),
	"ttd_link" varchar(500),
	"s3_upload_log" text,
	"approval" varchar(30),
	"approval_by" integer,
	"approval_date" timestamp,
	"approval_comment" varchar(500),
	"approval_actual" varchar(30),
	"approval_actual_by" integer,
	"approval_actual_date" timestamp,
	"approval_actual_comment" varchar(500),
	"join_visit" smallint DEFAULT 0,
	"join_visit_ff" varchar(30),
	"join_visit_id" uuid,
	"note" varchar(255),
	"created_by" integer,
	"updated_by" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "visit_tidak_kunjungan" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"periode" varchar(10) NOT NULL,
	"week" varchar(10) NOT NULL,
	"id_peg" integer,
	"id_ff" varchar(15),
	"nama" varchar(200),
	"divisi" varchar(50),
	"tanggal" date,
	"alasan" varchar(50),
	"keterangan" varchar(500),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "visit_tidak_kunjungan_mr" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"periode" varchar(10) NOT NULL,
	"week" varchar(10) NOT NULL,
	"id_peg" integer,
	"id_ff" varchar(15),
	"nama" varchar(200),
	"divisi" varchar(50),
	"tanggal" date,
	"alasan" varchar(50),
	"keterangan" varchar(250),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "call_list" ADD CONSTRAINT "call_list_id_mcl_list_dokter_visit_new_ID_fk" FOREIGN KEY ("id_mcl") REFERENCES "public"."list_dokter_visit_new"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "call_list" ADD CONSTRAINT "call_list_id_peg_data_pegawai_rowid_fk" FOREIGN KEY ("id_peg") REFERENCES "public"."data_pegawai"("rowid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "call_list_history" ADD CONSTRAINT "call_list_history_call_list_id_call_list_id_fk" FOREIGN KEY ("call_list_id") REFERENCES "public"."call_list"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "call_list_history" ADD CONSTRAINT "call_list_history_id_peg_data_pegawai_rowid_fk" FOREIGN KEY ("id_peg") REFERENCES "public"."data_pegawai"("rowid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "call_plan_actual" ADD CONSTRAINT "call_plan_actual_id_peg_data_pegawai_rowid_fk" FOREIGN KEY ("id_peg") REFERENCES "public"."data_pegawai"("rowid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "call_plan_actual" ADD CONSTRAINT "call_plan_actual_id_mcl_list_dokter_visit_new_ID_fk" FOREIGN KEY ("id_mcl") REFERENCES "public"."list_dokter_visit_new"("ID") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "call_plan_actual" ADD CONSTRAINT "call_plan_actual_join_visit_id_call_plan_actual_id_fk" FOREIGN KEY ("join_visit_id") REFERENCES "public"."call_plan_actual"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "visit_tidak_kunjungan" ADD CONSTRAINT "visit_tidak_kunjungan_id_peg_data_pegawai_rowid_fk" FOREIGN KEY ("id_peg") REFERENCES "public"."data_pegawai"("rowid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "visit_tidak_kunjungan_mr" ADD CONSTRAINT "visit_tidak_kunjungan_mr_id_peg_data_pegawai_rowid_fk" FOREIGN KEY ("id_peg") REFERENCES "public"."data_pegawai"("rowid") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "app_modul_nama_unique" ON "app_modul" USING btree ("nama_modul");--> statement-breakpoint
CREATE UNIQUE INDEX "app_role_menu_unique" ON "app_role_menu" USING btree ("id_menu","id_modul","id_user");--> statement-breakpoint
CREATE INDEX "idx_call_target_class" ON "call_target_class" USING btree ("jabatan","class");--> statement-breakpoint
CREATE UNIQUE INDEX "data_product_unique" ON "data_product" USING btree ("id_product","jenis_product","sub_divisi","divisi","periode_awal");--> statement-breakpoint
CREATE UNIQUE INDEX "data_spec_dr_unique" ON "data_spec_dr" USING btree ("spec");--> statement-breakpoint
CREATE UNIQUE INDEX "ldvn_id_peg_unique" ON "list_dokter_visit_new" USING btree ("ID_PEG","ID_FF","DIVISI","ID_MCL","KODE_OUTLET_UNION");--> statement-breakpoint
CREATE INDEX "idx_struktur_periode" ON "struktur" USING btree ("periode_akhir","id_peg_mr");--> statement-breakpoint
CREATE UNIQUE INDEX "users_username_unique" ON "users" USING btree ("username");--> statement-breakpoint
CREATE UNIQUE INDEX "call_list_idx" ON "call_list" USING btree ("id_mcl","periode","id_ff");--> statement-breakpoint
CREATE INDEX "call_list_peg_periode_idx" ON "call_list" USING btree ("id_peg","periode");--> statement-breakpoint
CREATE INDEX "call_list_approval_idx" ON "call_list" USING btree ("id_peg","periode","approval");--> statement-breakpoint
CREATE INDEX "clh_call_list_idx" ON "call_list_history" USING btree ("call_list_id");--> statement-breakpoint
CREATE INDEX "clh_peg_idx" ON "call_list_history" USING btree ("id_peg");--> statement-breakpoint
CREATE INDEX "clh_date_idx" ON "call_list_history" USING btree ("action_date");--> statement-breakpoint
CREATE UNIQUE INDEX "cpa_unique" ON "call_plan_actual" USING btree ("id_peg","tgl_actual","id_mcl");--> statement-breakpoint
CREATE INDEX "cpa_lookup_idx" ON "call_plan_actual" USING btree ("id_peg","id_mcl","tgl_actual","approval_actual");--> statement-breakpoint
CREATE INDEX "cpa_plan_idx" ON "call_plan_actual" USING btree ("id_peg","tgl_plan","approval");--> statement-breakpoint
CREATE INDEX "cpa_join_window_idx" ON "call_plan_actual" USING btree ("join_visit","updated_at");--> statement-breakpoint
CREATE UNIQUE INDEX "vtk_peg_tanggal_unique" ON "visit_tidak_kunjungan" USING btree ("id_peg","tanggal");--> statement-breakpoint
CREATE UNIQUE INDEX "vtk_mr_peg_tanggal_unique" ON "visit_tidak_kunjungan_mr" USING btree ("id_peg","tanggal");