import { pgTable, integer, varchar, date, timestamp, uniqueIndex } from 'drizzle-orm/pg-core';

export const data_product = pgTable(
  'data_product',
  {
    id: integer('id').primaryKey().generatedByDefaultAsIdentity(),
    id_product: varchar('id_product', { length: 25 }).notNull(),
    nama_product: varchar('nama_product', { length: 50 }).notNull(),
    komposisi: varchar('komposisi', { length: 400 }),
    kemasan: varchar('kemasan', { length: 70 }),
    isi_box: integer('isi_box'),
    group_product: varchar('group_product', { length: 30 }),
    jenis_product: varchar('jenis_product', { length: 15 }).notNull(),
    keterangan_harga: varchar('keterangan_harga', { length: 50 }),
    class_terapi: varchar('class_terapi', { length: 50 }),
    product_hj: varchar('product_hj', { length: 10 }),
    sub_divisi: varchar('sub_divisi', { length: 30 }),
    sub_divisi_sales: varchar('sub_divisi_sales', { length: 30 }),
    divisi: varchar('divisi', { length: 30 }).notNull(),
    set_divisi: varchar('set_divisi', { length: 30 }),
    harga: integer('harga').notNull(),
    harga_jadi: integer('harga_jadi'),
    harga_reg_1: integer('harga_reg_1'),
    harga_reg_2: integer('harga_reg_2'),
    harga_reg_3: integer('harga_reg_3'),
    harga_reg_4: integer('harga_reg_4'),
    harga_reg_5: integer('harga_reg_5'),
    harga_reg_6: integer('harga_reg_6'),
    harga_reg_7: integer('harga_reg_7'),
    penyeragaman_product: varchar('penyeragaman_product', { length: 50 }),
    brand_product: varchar('brand_product', { length: 50 }),
    product_fokus: varchar('product_fokus', { length: 20 }),
    periode_awal: date('periode_awal'),
    periode_akhir: date('periode_akhir'),
    status: varchar('status', { length: 20 }),
    attachment: varchar('attachment', { length: 250 }),
    product_detail_link: varchar('product_detail_link', { length: 255 }),
    tgl_masa_berlaku: date('tgl_masa_berlaku'),
    created_date: timestamp('created_date'),
    created_by: integer('created_by'),
    updated_date: timestamp('updated_date'),
    updated_by: integer('updated_by'),
  },
  (t) => ({
    idx_id_product_unique: uniqueIndex('data_product_unique').on(
      t.id_product,
      t.jenis_product,
      t.sub_divisi,
      t.divisi,
      t.periode_awal,
    ),
  }),
);
