import {
  pgTable,
  integer,
  varchar,
  text,
  date,
  time,
  timestamp,
  uniqueIndex,
} from 'drizzle-orm/pg-core';

export const list_dokter_visit_new = pgTable(
  'list_dokter_visit_new',
  {
    ID: integer('ID').primaryKey().generatedByDefaultAsIdentity(),
    ID_PEG: integer('ID_PEG').notNull(),
    ID_FF: varchar('ID_FF', { length: 15 }).notNull(),
    NAMA_FF: varchar('NAMA_FF', { length: 200 }).notNull(),
    RAYON: varchar('RAYON', { length: 200 }).notNull(),
    DISTRIK: varchar('DISTRIK', { length: 200 }).notNull(),
    REGION: varchar('REGION', { length: 30 }).notNull(),
    DIVISI: varchar('DIVISI', { length: 30 }).notNull(),
    SEGMEN_MD: integer('SEGMEN_MD').notNull(),
    ID_MCL: integer('ID_MCL').notNull(),
    ID_MD: varchar('ID_MD', { length: 30 }),
    NAMA_DOKTER: varchar('NAMA_DOKTER', { length: 200 }).notNull(),
    NAMA_NON_DOKTER: varchar('NAMA_NON_DOKTER', { length: 150 }),
    NO_STR: varchar('NO_STR', { length: 100 }),
    SPEC: varchar('SPEC', { length: 50 }).notNull(),
    CLASS: varchar('CLASS', { length: 5 }),
    KODE_OUTLET_UNION: varchar('KODE_OUTLET_UNION', { length: 20 }).notNull(),
    INSTITUSI: varchar('INSTITUSI', { length: 200 }),
    KOORDINAT_INSTITUSI: varchar('KOORDINAT_INSTITUSI', { length: 100 }),
    WILAYAH: varchar('WILAYAH', { length: 20 }),
    WILAYAH_DM: varchar('WILAYAH_DM', { length: 20 }),
    WILAYAH_RSM: varchar('WILAYAH_RSM', { length: 20 }),
    HARI_PRAKTEK: varchar('HARI_PRAKTEK', { length: 100 }),
    JAM_MULAI_PRAKTEK: time('JAM_MULAI_PRAKTEK'),
    JAM_SELESAI_PRAKTEK: time('JAM_SELESAI_PRAKTEK'),
    DURASI_PRAKTEK: varchar('DURASI_PRAKTEK', { length: 50 }),
    ALAMAT_PRAKTEK: varchar('ALAMAT_PRAKTEK', { length: 250 }),
    KOTA: varchar('KOTA', { length: 50 }),
    ALAMAT_RUMAH: text('ALAMAT_RUMAH'),
    NO_TELP_DOKTER: varchar('NO_TELP_DOKTER', { length: 15 }),
    HUT: date('HUT').notNull(),
    PROD_DETAILING_1: varchar('PROD_DETAILING_1', { length: 50 }),
    PROD_DETAILING_2: varchar('PROD_DETAILING_2', { length: 50 }),
    PROD_DETAILING_3: varchar('PROD_DETAILING_3', { length: 50 }),
    PROD_DETAILING_4: varchar('PROD_DETAILING_4', { length: 50 }),
    PROD_DETAILING_5: varchar('PROD_DETAILING_5', { length: 50 }),
    PROD_DETAILING_6: varchar('PROD_DETAILING_6', { length: 50 }),
    PROD_DETAILING_7: varchar('PROD_DETAILING_7', { length: 50 }),
    PROD_DETAILING_8: varchar('PROD_DETAILING_8', { length: 50 }),
    PROD_DETAILING_9: varchar('PROD_DETAILING_9', { length: 50 }),
    PROD_DETAILING_10: varchar('PROD_DETAILING_10', { length: 50 }),
    STATUS_MD: varchar('STATUS_MD', { length: 15 }),
    DIBERIKAN_RBP: varchar('DIBERIKAN_RBP', { length: 15 }),
    JENIS_RBP: varchar('JENIS_RBP', { length: 50 }),
    KETERANGAN: varchar('KETERANGAN', { length: 150 }),
    CREATED_DATE: timestamp('CREATED_DATE'),
    CREATED_BY: integer('CREATED_BY'),
    UPDATED_DATE: timestamp('UPDATED_DATE'),
    UPDATED_BY: integer('UPDATED_BY'),
    check_dm: integer('check_dm'),
    check_dm_date: timestamp('check_dm_date'),
    check_rsm: integer('check_rsm'),
    check_rsm_date: timestamp('check_rsm_date'),
    revisi_dm: integer('revisi_dm'),
    comment_revisi_dm: text('comment_revisi_dm'),
    revisi_rsm: integer('revisi_rsm'),
    comment_revisi_rsm: text('comment_revisi_rsm'),
    note: varchar('note', { length: 100 }),
  },
  (t) => ({
    idx_ldvn_unique: uniqueIndex('ldvn_id_peg_unique').on(
      t.ID_PEG,
      t.ID_FF,
      t.DIVISI,
      t.ID_MCL,
      t.KODE_OUTLET_UNION,
    ),
  }),
);
