/**
 * MASTER TABLES — mirror persis MariaDB legacy.
 *
 * Strategi: tabel ini di-sync 1:1 dari MariaDB `monitoring` via cron daily/weekly.
 * - PK pakai INT auto-increment (generated BY DEFAULT) sama dengan legacy.
 * - Kolom + nullability + tipe pertahankan persis.
 * - Sync UPSERT by `id` (atau PK setiap tabel).
 * - Tabel ini READ-ONLY dari sisi new mobile API — semua tulis lewat cron.
 *
 * Catatan nama kolom UPPERCASE (mis. list_dokter_visit_new.ID) sengaja
 * dipertahankan supaya identik dengan legacy → Drizzle akan quote
 * identifier-nya di SQL.
 */

import {
  pgTable,
  integer,
  bigint,
  varchar,
  text,
  date,
  time,
  timestamp,
  uniqueIndex,
  index,
} from 'drizzle-orm/pg-core';

// ============================================================================
// users — login account
// ============================================================================
export const users = pgTable(
  'users',
  {
    id: bigint('id', { mode: 'number' }).primaryKey().generatedByDefaultAsIdentity(),
    name: varchar('name', { length: 255 }).notNull(),
    username: varchar('username', { length: 150 }).notNull(),
    status: varchar('status', { length: 15 }),
    email: varchar('email', { length: 255 }),
    email_verified_at: timestamp('email_verified_at'),
    password: varchar('password', { length: 255 }).notNull(),
    password_view: varchar('password_view', { length: 100 }),
    remember_token: varchar('remember_token', { length: 100 }),
    created_at: timestamp('created_at'),
    updated_at: timestamp('updated_at'),
  },
  (t) => ({
    username_unique: uniqueIndex('users_username_unique').on(t.username),
  }),
);

// ============================================================================
// data_pegawai — master pegawai (rowid = id_peg di mobile)
// ============================================================================
export const data_pegawai = pgTable('data_pegawai', {
  rowid: integer('rowid').primaryKey().generatedByDefaultAsIdentity(),
  id: varchar('id', { length: 10 }).notNull(), // id_ff (kode pegawai, bukan numeric)
  nik: varchar('nik', { length: 20 }),
  nama: varchar('nama', { length: 200 }).notNull(),
  jabatan: varchar('jabatan', { length: 50 }).notNull(),
  divisi: varchar('divisi', { length: 30 }),
  rayon: varchar('rayon', { length: 200 }),
  rayon_dm: varchar('rayon_dm', { length: 150 }),
  region: varchar('region', { length: 50 }),
  homebase: varchar('homebase', { length: 50 }),
  lokasi: varchar('lokasi', { length: 30 }),
  lokasi_absen: varchar('lokasi_absen', { length: 30 }),
  telepon: varchar('telepon', { length: 30 }),
  email: varchar('email', { length: 250 }),
  status: varchar('status', { length: 20 }),
  keterangan: varchar('keterangan', { length: 200 }),
  tgl_masuk: date('tgl_masuk'),
  tgl_keluar: date('tgl_keluar'),
  tanda_tangan: varchar('tanda_tangan', { length: 50 }),
  id_finger: integer('id_finger'),
  id_user: integer('id_user'),
});

// ============================================================================
// struktur — hierarki organisasi MR → DM → RSM → MM per periode
// ============================================================================
export const struktur = pgTable(
  'struktur',
  {
    id: integer('id').primaryKey().generatedByDefaultAsIdentity(),
    id_mr: varchar('id_mr', { length: 15 }),
    id_peg_mr: integer('id_peg_mr'),
    rayon_mr: varchar('rayon_mr', { length: 220 }).notNull(),
    golongan: varchar('golongan', { length: 15 }).notNull(),
    divisi: varchar('divisi', { length: 20 }).notNull(),
    id_dm: varchar('id_dm', { length: 15 }),
    id_peg_dm: integer('id_peg_dm'),
    rayon_dm: varchar('rayon_dm', { length: 100 }).notNull(),
    id_rsm: varchar('id_rsm', { length: 15 }),
    id_peg_rsm: integer('id_peg_rsm'),
    region: varchar('region', { length: 15 }).notNull(),
    id_som: varchar('id_som', { length: 15 }),
    id_peg_som: integer('id_peg_som'),
    id_mm: varchar('id_mm', { length: 15 }),
    id_peg_mm: integer('id_peg_mm'),
    id_dmd: varchar('id_dmd', { length: 15 }),
    id_peg_dmd: integer('id_peg_dmd'),
    id_md: varchar('id_md', { length: 15 }),
    id_peg_md: integer('id_peg_md'),
    id_vp: varchar('id_vp', { length: 15 }),
    id_peg_vp: integer('id_peg_vp'),
    id_adminda: varchar('id_adminda', { length: 15 }),
    kantor_cabang: varchar('kantor_cabang', { length: 25 }),
    periode_awal: date('periode_awal').notNull(),
    periode_akhir: date('periode_akhir').notNull(),
    created_date: timestamp('created_date'),
    created_by: integer('created_by'),
    updated_date: timestamp('updated_date'),
    updated_by: integer('updated_by'),
  },
  (t) => ({
    idx_struktur_periode: index('idx_struktur_periode').on(t.periode_akhir, t.id_peg_mr),
  }),
);

// ============================================================================
// app_modul — master modul
// ============================================================================
export const app_modul = pgTable(
  'app_modul',
  {
    id_modul: integer('id_modul').primaryKey().generatedByDefaultAsIdentity(),
    nama_modul: varchar('nama_modul', { length: 25 }).notNull(),
    icons: varchar('icons', { length: 30 }).notNull(),
    icons2: varchar('icons2', { length: 30 }),
    color: varchar('color', { length: 20 }),
  },
  (t) => ({
    nama_modul_unique: uniqueIndex('app_modul_nama_unique').on(t.nama_modul),
  }),
);

// ============================================================================
// app_role_menu — akses modul per user
// ============================================================================
export const app_role_menu = pgTable(
  'app_role_menu',
  {
    id_role: integer('id_role').primaryKey().generatedByDefaultAsIdentity(),
    id_menu: integer('id_menu').notNull(),
    id_modul: integer('id_modul').notNull(),
    id_user: integer('id_user').notNull(),
  },
  (t) => ({
    idx_role_unique: uniqueIndex('app_role_menu_unique').on(t.id_menu, t.id_modul, t.id_user),
  }),
);

// ============================================================================
// call_version — gate versi mobile (untuk dialog update wajib)
// ============================================================================
export const call_version = pgTable('call_version', {
  id: integer('id').primaryKey().generatedByDefaultAsIdentity(),
  version: varchar('version', { length: 20 }),
  link_apk: varchar('link_apk', { length: 100 }),
});

// ============================================================================
// list_dokter_visit_new — master dokter/customer (UPPERCASE kolom intentional)
// ============================================================================
export const list_dokter_visit_new = pgTable(
  'list_dokter_visit_new',
  {
    ID: integer('ID').primaryKey().generatedByDefaultAsIdentity(),
    ID_PEG: integer('ID_PEG').notNull(),
    ID_FF: varchar('ID_FF', { length: 15 }).notNull(),
    NAMA_FF: varchar('NAMA_FF', { length: 200 }).notNull(),
    RAYON: varchar('RAYON', { length: 200 }).notNull(),
    DISTRIK: varchar('DISTRIK', { length: 200 }).notNull(),
    REGION: varchar('REGION', { length: 30 }).notNull(),
    DIVISI: varchar('DIVISI', { length: 30 }).notNull(),
    SEGMEN_MD: integer('SEGMEN_MD').notNull(),
    ID_MCL: integer('ID_MCL').notNull(),
    ID_MD: varchar('ID_MD', { length: 30 }),
    NAMA_DOKTER: varchar('NAMA_DOKTER', { length: 200 }).notNull(),
    NAMA_NON_DOKTER: varchar('NAMA_NON_DOKTER', { length: 150 }),
    NO_STR: varchar('NO_STR', { length: 100 }),
    SPEC: varchar('SPEC', { length: 50 }).notNull(),
    CLASS: varchar('CLASS', { length: 5 }),
    KODE_OUTLET_UNION: varchar('KODE_OUTLET_UNION', { length: 20 }).notNull(),
    INSTITUSI: varchar('INSTITUSI', { length: 200 }),
    KOORDINAT_INSTITUSI: varchar('KOORDINAT_INSTITUSI', { length: 100 }),
    WILAYAH: varchar('WILAYAH', { length: 20 }),
    WILAYAH_DM: varchar('WILAYAH_DM', { length: 20 }),
    WILAYAH_RSM: varchar('WILAYAH_RSM', { length: 20 }),
    HARI_PRAKTEK: varchar('HARI_PRAKTEK', { length: 100 }),
    JAM_MULAI_PRAKTEK: time('JAM_MULAI_PRAKTEK'),
    JAM_SELESAI_PRAKTEK: time('JAM_SELESAI_PRAKTEK'),
    DURASI_PRAKTEK: varchar('DURASI_PRAKTEK', { length: 50 }),
    ALAMAT_PRAKTEK: varchar('ALAMAT_PRAKTEK', { length: 250 }),
    KOTA: varchar('KOTA', { length: 50 }),
    ALAMAT_RUMAH: text('ALAMAT_RUMAH'),
    NO_TELP_DOKTER: varchar('NO_TELP_DOKTER', { length: 15 }),
    HUT: date('HUT').notNull(),
    PROD_DETAILING_1: varchar('PROD_DETAILING_1', { length: 50 }),
    PROD_DETAILING_2: varchar('PROD_DETAILING_2', { length: 50 }),
    PROD_DETAILING_3: varchar('PROD_DETAILING_3', { length: 50 }),
    PROD_DETAILING_4: varchar('PROD_DETAILING_4', { length: 50 }),
    PROD_DETAILING_5: varchar('PROD_DETAILING_5', { length: 50 }),
    PROD_DETAILING_6: varchar('PROD_DETAILING_6', { length: 50 }),
    PROD_DETAILING_7: varchar('PROD_DETAILING_7', { length: 50 }),
    PROD_DETAILING_8: varchar('PROD_DETAILING_8', { length: 50 }),
    PROD_DETAILING_9: varchar('PROD_DETAILING_9', { length: 50 }),
    PROD_DETAILING_10: varchar('PROD_DETAILING_10', { length: 50 }),
    STATUS_MD: varchar('STATUS_MD', { length: 15 }),
    DIBERIKAN_RBP: varchar('DIBERIKAN_RBP', { length: 15 }),
    JENIS_RBP: varchar('JENIS_RBP', { length: 50 }),
    KETERANGAN: varchar('KETERANGAN', { length: 150 }),
    CREATED_DATE: timestamp('CREATED_DATE'),
    CREATED_BY: integer('CREATED_BY'),
    UPDATED_DATE: timestamp('UPDATED_DATE'),
    UPDATED_BY: integer('UPDATED_BY'),
    check_dm: integer('check_dm'),
    check_dm_date: timestamp('check_dm_date'),
    check_rsm: integer('check_rsm'),
    check_rsm_date: timestamp('check_rsm_date'),
    revisi_dm: integer('revisi_dm'),
    comment_revisi_dm: text('comment_revisi_dm'),
    revisi_rsm: integer('revisi_rsm'),
    comment_revisi_rsm: text('comment_revisi_rsm'),
    note: varchar('note', { length: 100 }),
  },
  (t) => ({
    idx_ldvn_unique: uniqueIndex('ldvn_id_peg_unique').on(
      t.ID_PEG,
      t.ID_FF,
      t.DIVISI,
      t.ID_MCL,
      t.KODE_OUTLET_UNION,
    ),
  }),
);

// ============================================================================
// call_setting — konfigurasi rule bisnis
// ============================================================================
export const call_setting = pgTable('call_setting', {
  id: integer('id').primaryKey().generatedByDefaultAsIdentity(),
  user: integer('user'),
  nama: varchar('nama', { length: 75 }),
  bulan: varchar('bulan', { length: 20 }),
  input_set: varchar('input_set', { length: 50 }),
  jumlah: integer('jumlah'),
  created_date: timestamp('created_date'),
  created_by: integer('created_by'),
  updated_date: timestamp('updated_date'),
  updated_by: integer('updated_by'),
});

// ============================================================================
// call_target_list — target dokter/non-dokter per (jabatan, divisi)
// ============================================================================
export const call_target_list = pgTable('call_target_list', {
  id: integer('id').primaryKey().generatedByDefaultAsIdentity(),
  jabatan: varchar('jabatan', { length: 20 }).notNull(),
  divisi: varchar('divisi', { length: 50 }).notNull(),
  dokter: integer('dokter').notNull(),
  non_dokter: integer('non_dokter'),
  periode_awal: date('periode_awal'),
  periode_akhir: date('periode_akhir'),
});

// ============================================================================
// call_target_hari — target per hari per (jabatan, divisi)
// ============================================================================
export const call_target_hari = pgTable('call_target_hari', {
  id: integer('id').primaryKey().generatedByDefaultAsIdentity(),
  jabatan: varchar('jabatan', { length: 20 }).notNull(),
  divisi: varchar('divisi', { length: 50 }).notNull(),
  dokter: integer('dokter').notNull(),
  non_dokter: integer('non_dokter'),
  periode_awal: date('periode_awal'),
  periode_akhir: date('periode_akhir'),
});

// ============================================================================
// call_target_class — target frekuensi per class
// ============================================================================
export const call_target_class = pgTable(
  'call_target_class',
  {
    id: integer('id').primaryKey().generatedByDefaultAsIdentity(),
    jabatan: varchar('jabatan', { length: 15 }).notNull(),
    class: varchar('class', { length: 5 }).notNull(),
    target: integer('target').notNull(),
  },
  (t) => ({
    idx_ctc: index('idx_call_target_class').on(t.jabatan, t.class),
  }),
);

// ============================================================================
// data_product — master produk
// ============================================================================
export const data_product = pgTable(
  'data_product',
  {
    id: integer('id').primaryKey().generatedByDefaultAsIdentity(),
    id_product: varchar('id_product', { length: 25 }).notNull(),
    nama_product: varchar('nama_product', { length: 50 }).notNull(),
    komposisi: varchar('komposisi', { length: 400 }),
    kemasan: varchar('kemasan', { length: 70 }),
    isi_box: integer('isi_box'),
    group_product: varchar('group_product', { length: 30 }),
    jenis_product: varchar('jenis_product', { length: 15 }).notNull(),
    keterangan_harga: varchar('keterangan_harga', { length: 50 }),
    class_terapi: varchar('class_terapi', { length: 50 }),
    product_hj: varchar('product_hj', { length: 10 }),
    sub_divisi: varchar('sub_divisi', { length: 30 }),
    sub_divisi_sales: varchar('sub_divisi_sales', { length: 30 }),
    divisi: varchar('divisi', { length: 30 }).notNull(),
    set_divisi: varchar('set_divisi', { length: 30 }),
    harga: integer('harga').notNull(),
    harga_jadi: integer('harga_jadi'),
    harga_reg_1: integer('harga_reg_1'),
    harga_reg_2: integer('harga_reg_2'),
    harga_reg_3: integer('harga_reg_3'),
    harga_reg_4: integer('harga_reg_4'),
    harga_reg_5: integer('harga_reg_5'),
    harga_reg_6: integer('harga_reg_6'),
    harga_reg_7: integer('harga_reg_7'),
    penyeragaman_product: varchar('penyeragaman_product', { length: 50 }),
    brand_product: varchar('brand_product', { length: 50 }),
    product_fokus: varchar('product_fokus', { length: 20 }),
    periode_awal: date('periode_awal'),
    periode_akhir: date('periode_akhir'),
    status: varchar('status', { length: 20 }),
    attachment: varchar('attachment', { length: 250 }),
    product_detail_link: varchar('product_detail_link', { length: 255 }),
    tgl_masa_berlaku: date('tgl_masa_berlaku'),
    created_date: timestamp('created_date'),
    created_by: integer('created_by'),
    updated_date: timestamp('updated_date'),
    updated_by: integer('updated_by'),
  },
  (t) => ({
    idx_id_product_unique: uniqueIndex('data_product_unique').on(
      t.id_product,
      t.jenis_product,
      t.sub_divisi,
      t.divisi,
      t.periode_awal,
    ),
  }),
);

// ============================================================================
// data_spec_dr — spesialisasi dokter (dropdown)
// ============================================================================
export const data_spec_dr = pgTable(
  'data_spec_dr',
  {
    id: integer('id').primaryKey().generatedByDefaultAsIdentity(),
    spec: varchar('spec', { length: 50 }).notNull(),
    gelar: varchar('gelar', { length: 20 }),
    keterangan: varchar('keterangan', { length: 50 }),
  },
  (t) => ({
    spec_unique: uniqueIndex('data_spec_dr_unique').on(t.spec),
  }),
);
