import { pgTable, integer, varchar, date, timestamp, index } from 'drizzle-orm/pg-core';

export const struktur = pgTable(
  'struktur',
  {
    id: integer('id').primaryKey().generatedByDefaultAsIdentity(),
    id_mr: varchar('id_mr', { length: 15 }),
    id_peg_mr: integer('id_peg_mr'),
    rayon_mr: varchar('rayon_mr', { length: 220 }).notNull(),
    golongan: varchar('golongan', { length: 15 }).notNull(),
    divisi: varchar('divisi', { length: 20 }).notNull(),
    id_dm: varchar('id_dm', { length: 15 }),
    id_peg_dm: integer('id_peg_dm'),
    rayon_dm: varchar('rayon_dm', { length: 100 }).notNull(),
    id_rsm: varchar('id_rsm', { length: 15 }),
    id_peg_rsm: integer('id_peg_rsm'),
    region: varchar('region', { length: 15 }).notNull(),
    id_som: varchar('id_som', { length: 15 }),
    id_peg_som: integer('id_peg_som'),
    id_mm: varchar('id_mm', { length: 15 }),
    id_peg_mm: integer('id_peg_mm'),
    id_dmd: varchar('id_dmd', { length: 15 }),
    id_peg_dmd: integer('id_peg_dmd'),
    id_md: varchar('id_md', { length: 15 }),
    id_peg_md: integer('id_peg_md'),
    id_vp: varchar('id_vp', { length: 15 }),
    id_peg_vp: integer('id_peg_vp'),
    id_adminda: varchar('id_adminda', { length: 15 }),
    kantor_cabang: varchar('kantor_cabang', { length: 25 }),
    periode_awal: date('periode_awal').notNull(),
    periode_akhir: date('periode_akhir').notNull(),
    created_date: timestamp('created_date'),
    created_by: integer('created_by'),
    updated_date: timestamp('updated_date'),
    updated_by: integer('updated_by'),
  },
  (t) => ({
    idx_struktur_periode: index('idx_struktur_periode').on(t.periode_akhir, t.id_peg_mr),
  }),
);
