services:
  postgres:
    image: postgres:16-alpine
    container_name: msf-pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: msf
      POSTGRES_PASSWORD: msf
      POSTGRES_DB: msf
      TZ: Asia/Jakarta
      PGTZ: Asia/Jakarta
    ports:
      - "5432:5432"
    volumes:
      - msf-pg-data:/var/lib/postgresql/data
      - ./docker/initdb:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U msf -d msf"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  msf-pg-data:
